version: '3'
services:
  frontend:
    build: ./frontend # our frontend file
    
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules   #to ignore node_modules folder while mapping
      - ./frontend:/app 
    environment:
      - CHOKIDAR_USEPOLLING=true
    
  api:
    build: ./api # our frontend file
    ports: 
      - "5050:5050"
    volumes:
      - ./api:/app 